language: php
php:
- 5.5
- 5.6
install: composer install
env:
  global:
  - secure: mG5krlJyx6Vs6xHp1STyRvitUB0+JV9mibA6Da7+D5MRvEu/6FirpMbR3ELZ/T7XZ8YmuLB/w++8aaD5uscNClzkbW6rKWj4FahRWDMfYjqNWtTOHLdHFuq+5Egs2o5vHCCl7eoAfNHlCbGfEZbN9qaMur/CJqfzw2ZkHdMhnI0=
  - secure: cbyAQNZENrhfmPb20tMfJlwv5W/6XELybJ+oH9y+Qyi/SSnYiXvPtsCPFplYqd6UCxup+wfSHay8/68MBW0vnXZpAZ/T9sOzHIp4PGPKKjZXIe+XrvhaAGacBpsNdEhW4SCAZSm9rOoArmgGcIqJ+Ynl5xWbqU5K7JLphczYmTY=
script:
- ./vendor/bin/phing test
notifications:
  email:
    recipients:
    - bert@2dotstwice.be
  hipchat:
    rooms:
      secure: PHFM1l1L8EZ/Bw9NTNWFjyCvoP/hRdDskX4vK9wYCwlQLAHYBdqX8RcNkdBWHQG1Be4goq8wV1yh9sXs3GN1I3pY5MQyQxPgZgV9DmMZOZC+ByVr73KTcC9kznPzAKpCZRcYqTGTlYh2JctBoVBN2nGwoQ0YmvwlIHIYOXz3vxY=
